// SPDX-License-Identifier: GPL-2.0-only
/*
 * Copyright (c) 2021, Konrad Dybcio <konrad.dybcio@somainline.org>
 * Copyright (c) 2021, Ivaylo Ivanov <ivo.ivanov@null.net>
 */

#ifndef _DT_BINDINGS_CLK_MSM_GCC_8610_H
#define _DT_BINDINGS_CLK_MSM_GCC_8610_H

#define GPLL0					0
#define BLSP1_QUP1_SPI_APPS_CLK_SRC		1
#define BLSP1_QUP2_SPI_APPS_CLK_SRC		2
#define BLSP1_QUP3_SPI_APPS_CLK_SRC		3
#define BLSP1_QUP4_SPI_APPS_CLK_SRC		4
#define BLSP1_QUP5_SPI_APPS_CLK_SRC		5
#define BLSP1_QUP6_SPI_APPS_CLK_SRC		6
#define BLSP1_QUP1_I2C_APPS_CLK_SRC		7
#define BLSP1_QUP2_I2C_APPS_CLK_SRC		8
#define BLSP1_QUP3_I2C_APPS_CLK_SRC		9
#define BLSP1_QUP4_I2C_APPS_CLK_SRC		10
#define BLSP1_QUP5_I2C_APPS_CLK_SRC		11
#define BLSP1_QUP6_I2C_APPS_CLK_SRC		12
#define BLSP1_UART1_APPS_CLK_SRC		13
#define BLSP1_UART2_APPS_CLK_SRC		14
#define BLSP1_UART3_APPS_CLK_SRC		15
#define BLSP1_UART4_APPS_CLK_SRC		16
#define BLSP1_UART5_APPS_CLK_SRC		17
#define BLSP1_UART6_APPS_CLK_SRC		18
#define CE1_CLK_SRC				19
#define GP1_CLK_SRC				20
#define GP2_CLK_SRC				21
#define GP3_CLK_SRC				22
#define PDM2_CLK_SRC				23
#define SDCC1_APPS_CLK_SRC			24
#define SDCC2_APPS_CLK_SRC			25
#define USB_HS_SYSTEM_CLK_SRC			26
#define GCC_BLSP1_AHB_CLK			27
#define GCC_BLSP1_SLEEP_CLK			28
#define GCC_BLSP1_QUP1_SPI_APPS_CLK		29
#define GCC_BLSP1_QUP2_SPI_APPS_CLK		30
#define GCC_BLSP1_QUP3_SPI_APPS_CLK		31
#define GCC_BLSP1_QUP4_SPI_APPS_CLK		32
#define GCC_BLSP1_QUP5_SPI_APPS_CLK		33
#define GCC_BLSP1_QUP6_SPI_APPS_CLK		34
#define GCC_BLSP1_QUP1_I2C_APPS_CLK		35
#define GCC_BLSP1_QUP2_I2C_APPS_CLK		36
#define GCC_BLSP1_QUP3_I2C_APPS_CLK		37
#define GCC_BLSP1_QUP4_I2C_APPS_CLK		38
#define GCC_BLSP1_QUP5_I2C_APPS_CLK		39
#define GCC_BLSP1_QUP6_I2C_APPS_CLK		40
#define GCC_BLSP1_UART1_APPS_CLK		41
#define GCC_BLSP1_UART2_APPS_CLK		42
#define GCC_BLSP1_UART3_APPS_CLK		43
#define GCC_BLSP1_UART4_APPS_CLK		44
#define GCC_BLSP1_UART5_APPS_CLK		45
#define GCC_BLSP1_UART6_APPS_CLK		46
#define GCC_BOOT_ROM_AHB_CLK			47
#define GCC_CE1_AHB_CLK			48
#define GCC_CE1_AXI_CLK			49
#define GCC_CE1_CLK				50
#define GCC_COPSS_SMMU_AHB_CLK			51
#define GCC_LPSS_SMMU_AHB_CLK			52
#define GCC_MSS_CFG_AHB_CLK			53
#define GCC_GP1_CLK				54
#define GCC_GP2_CLK				55
#define GCC_GP3_CLK				56
#define GCC_LPASS_Q6_AXI_CLK			57
#define GCC_MSS_Q6_BIMC_AXI_CLK		58
#define GCC_PDM2_CLK				59
#define GCC_PDM_AHB_CLK			60
#define GCC_PRNG_AHB_CLK			61
#define GCC_SDCC1_AHB_CLK			62
#define GCC_SDCC2_AHB_CLK			63
#define GCC_SDCC1_APPS_CLK			64
#define GCC_SDCC2_APPS_CLK			65
#define GCC_USB2A_PHY_SLEEP_CLK		66
#define GCC_USB_HS_AHB_CLK			67
#define GCC_USB_HS_SYSTEM_CLK			68
#define GCC_BIMC_SMMU_CLK			69

#endif
